### ISSUE TITLE
Consolidate ICT skill list present in .json datafiles

### ISSUE THREAD

**Issue by ioggstream** [par-tec/esco-playground#25]
## I expect

- [ ] that all skills referenced in ICT occupations (e.g., https://esco.ec.europa.eu/en/classification/skills?uri=http://data.europa.eu/esco/isco/C25) are present in .json datafiles
- [ ] this presence should be tested by a specific test file.

## Instead

- there is no test to find that the list of those skills is completely mentioned in esco.json

## Note

This could be useful to generalize (e.g., using a sparql server) the matcher for a given sector.

**Comment by Edocampa** [comment]
Ho provato a verificare che le skill riferite a quelle occupazioni ci fossero nel json file ma la seguente query sparql non ha restituito risultati:

prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix esco: <http://data.europa.eu/esco/model#>

SELECT DISTINCT ?skill ?label
WHERE {
  <http://data.europa.eu/esco/isco/C25> a esco:Occupation ;
                         (esco:relatedOptionalSkill|esco:relatedEssentialSkill) ?skill .
  
  ?skill skos:prefLabel ?label .
}

**Comment by Edocampa** [comment]
Ho provato a verificare che le skill riferite a quelle occupazioni ci fossero nel json file ma la seguente query sparql non ha restituito risultati:

prefix skos: http://www.w3.org/2004/02/skos/core#
prefix esco: http://data.europa.eu/esco/model#

SELECT DISTINCT ?skill ?label
WHERE {
http://data.europa.eu/esco/isco/C25 a esco:Occupation ;
(esco:relatedOptionalSkill|esco:relatedEssentialSkill) ?skill .

?skill skos:prefLabel ?label .
}

**Comment by ioggstream** [comment]
1. you are asking that
```
SELECT * WHERE { http://data.europa.eu/esco/isco/C25 a esco:Occupation }
```

but what happens if you

```
SELECT * WHERE { <http://data.europa.eu/esco/isco/C25> rdf:type ?q } 
```

**Comment by Edocampa** [comment]
I write this query Sparql that print occupations, essentialSkill and optionalSkill considering the concept ISCO 25:

PREFIX esco: <http://data.europa.eu/esco/model#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?occupationLabel ?occupation ?skillEssenziale ?skillOpzionale
WHERE {

  VALUES ?category {
    <http://data.europa.eu/esco/isco/C25>
  }

?occupation a esco:Occupation ;
skos:prefLabel ?occupationLabel ;
skos:broaderTransitive* ?category  .

OPTIONAL {
?occupation esco:relatedEssentialSkill ?skillEssenziale .
?skillEssenziale skos:prefLabel ?essenzialeLabel .
}

OPTIONAL {
?occupation esco:reatedOptionaSkill ?skillOpzionale .
?skillOpzionale skos:prefLabel ?opzionaleLabel .
}

}

**Comment by ioggstream** [comment]
Can you dump a list of skills instead of a table? I just want a list of skills

**Comment by Edocampa** [comment]
This query that I wrote returns a list of skills with optional labels (so if a skill does not have a label, null will be printed) considering the ISCO 25 concept:
 

PREFIX esco: <http://data.europa.eu/esco/model#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?skill ?label
WHERE {

  VALUES ?category {
    <http://data.europa.eu/esco/isco/C25>
  }

  ?occupation a esco:Occupation ;
  skos:broaderTransitive* ?category  .

  ?occupation ?relation ?skill .
  ?skill a skos:Concept .
  
  OPTIONAL { ?skill skos:prefLabel ?label . FILTER (lang(?label) = "en") }

  FILTER (?relation = esco:relatedEssentialSkill || ?relation = esco:relatedOptionalSkill)

}
